### ISSUE TITLE
Hiding entity properties

### ISSUE THREAD

**Issue by iSosnitsky** [darrachequesne/spring-data-jpa-datatables-sample#11]
Hi, i tried putting @JsonIgnoreProperties on entity field, but DataTablesRepository still outputs this field, despite the ignore annotation. That's pretty much the issue. 
If hiding a property is done in some other fashion when using this plugin - how do i do that?

**Comment by sebasira** [comment]
same here!

**Comment by darrachequesne** [comment]
As said [here](https://github.com/darrachequesne/spring-data-jpa-datatables/issues/79), I'm not able to reproduce your issue, neither with `@JsonIgnore / @JsonIgnoreProperties` or with `@JsonView`, which seem to work on my side. Are you able to reproduce by forking this repository?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
