### ISSUE TITLE
Still error

### ISSUE THREAD

**Issue by hendisantika** [darrachequesne/spring-data-jpa-datatables-sample#13]
I think I already followed the docs.
But Why I still got error:

https://github.com/hendisantika/SpringBoot-DataTable

![image](https://user-images.githubusercontent.com/3713580/92824982-41871700-f3f9-11ea-92a2-4e652dc11e03.png)

![image](https://user-images.githubusercontent.com/3713580/92825000-46e46180-f3f9-11ea-874c-f75486647416.png)

Any suggestion?

**Comment by orpham** [comment]
Have you included ` jquery.spring-friendly.js`?

**Comment by hendisantika** [comment]
I already added jquery.spring-friendly.js.
But, it's still error.

**Comment by darrachequesne** [comment]
Hi, thanks for providing a way to reproduce. It seems your table is declared twice: [here](https://github.com/hendisantika/SpringBoot-DataTable/blob/master/src/main/resources/static/js/index.js#L2) and [here](https://github.com/hendisantika/SpringBoot-DataTable/blob/master/src/main/resources/static/js/index.js#L74).

I think the first one should rather be `var table = $('table#sample').DataTable({ ... })`, and you can delete the second one.

**Comment by hendisantika** [comment]
Oooo... Even after I remove my second table. It doesn't work.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/3713580/93019469-66e67180-f601-11ea-92af-f0602ee93413.png">

**Comment by darrachequesne** [comment]
I've forked your repository and made the necessary updates: https://github.com/darrachequesne/SpringBoot-DataTable ([diff](https://github.com/darrachequesne/SpringBoot-DataTable/commit/15d862e4b5100cfa12068f0aadd28a4893cd9518))

And it seems to work for me:

![image](https://user-images.githubusercontent.com/13031701/93030072-8f319880-f620-11ea-858b-975a5f2e8e68.png)

Could you please check?

**Comment by hendisantika** [comment]
Hmmm.... It's weird.

Let me check & compare.

**Comment by hendisantika** [comment]
Now, it's working.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3713580/93030214-85715a80-f64b-11ea-837d-eef335b031e0.png">

Thank You @darrachequesne .

**Comment by hendisantika** [comment]
I close the issue then.
