### ISSUE TITLE
Jpa Repository 

### ISSUE THREAD

**Issue by maoneid** [darrachequesne/spring-data-jpa-datatables-sample#14]
Why does not this package for Datatable inherited from JpaRepository?

**Comment by darrachequesne** [comment]
For future readers, please see here: https://github.com/darrachequesne/spring-data-jpa-datatables/blob/5c41f34605b292fb2322e6348eba23108247ccef/src/main/java/org/springframework/data/jpa/datatables/repository/DataTablesRepositoryImpl.java#L23
