### ISSUE TITLE
column with data= null 

### ISSUE THREAD

**Issue by jzlima** [darrachequesne/spring-data-jpa-datatables-sample#6]
when i create a column with null data like below example to detail row an error was showed: 

org.springframework.beans.InvalidPropertyException: Invalid property 'columns[0][data]' of bean class [org.springframework.data.jpa.datatables.mapping.DataTablesInput]: Property referenced in indexed property path 'columns[0][data]' is neither an array nor a List nor a Map; returned value was [ColumnParameter [data=null, name=null, searchable=null, orderable=null, search=null]]

site datatables with expample null column : [datatables.net example row detail](https://datatables.net/examples/server_side/row_details.html)

```
...
  "processing": true,
                        'serverSide': true,
                        "columns": [
                            {"data": null,
                                "className": 'details-control',
                                "orderable": false,                                
                                "defaultContent": ''
                            },
.... 
                        ]
```

**Comment by darrachequesne** [comment]
Hi! Did you follow the instructions [here](https://github.com/darrachequesne/spring-data-jpa-datatables#4-include-jqueryspring-friendlyjs)?

According to the exception, it seems there is a mapping issue (which may not be related to the `null` data).

**Comment by tareq021** [comment]
Can you please look into this issue on [StackOverFlow](http://stackoverflow.com/questions/42509850/spring-boot-jquery-datatable-find-by-property)

**Comment by darrachequesne** [comment]
@tareq021 please read the instructions [here](https://github.com/darrachequesne/spring-data-jpa-datatables#4-include-jqueryspring-friendlyjs).

**Comment by jsnjfz** [comment]
You need to include 'jquery.spring-friendly.js'.
