### ISSUE TITLE
dropdown-search-improper results

### ISSUE THREAD

**Issue by sarath-s** [darrachequesne/spring-data-jpa-datatables-sample#9]
->implemented serverside filtering for datatables with the support of the dependency,
<dependency>
<groupId>com.github.darrachequesne</groupId>
<artifactId>spring-data-jpa-datatables</artifactId>
<version>4.3</version>
</dependency>
it went really well thanks for the wonderful library and example.
But face two issues.
1)if the indiviudal column dropdown search value is '0'(zero number) then the search method not working for individual column.

  var val = $.fn.dataTable.util.escapeRegex($(this).val());
  column.search( this.value ).draw();

2)For ineger values, for example column data is 1liter,12liter,111liter,30litter, when dropdown selected for 1litter , the result show all (1liter,12liter,111liter,).

thanks alot for given time to read the issue, will be very helpful if resolution is suggested.

**Comment by darrachequesne** [comment]
Did you find a solution for your problem?

For 1, I guess you need to add a special case for the `0` option?
For 2, the query is `SELECT .. FROM .. WHERE attr LIKE '%1liter%"`, which should explain your issue.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
